module Main

from "number" include Number

let gaussLegendre = (iterations) => {
    let mut a = 1.0
    let mut b = 1.0 / Number.sqrt(2.0)
    let mut p = 1.0
    let mut t = 0.25

    for (let mut i = 0; i < iterations; i += 1) {
        let an = a

        a = (a + b) / 2.0
        b = Number.sqrt(an * b)
        // using (an - a) ** 2 here produces a worse result
        t = t - p * (an - a) * (an - a)
        p *= 2.0
    }

    (a + b) ** 2.0 / (4.0 * t)
}

print(gaussLegendre(10))
